### ISSUE TITLE
Bad hash parameter when uploading to redacted 

### ISSUE THREAD

**Issue by LennyPenny** [karamanolev/WhatManager2#102]
```[2017-10-21 18:02:23,300: WARNING/PoolWorker-1] Progress: V0 - uploading to Redacted
[2017-10-21 18:02:23,304: WARNING/PoolWorker-1] Sending request for upload to Redacted
[2017-10-21 18:02:27,278: WARNING/PoolWorker-1] bad hash parameter
[2017-10-21 18:02:27,278: WARNING/PoolWorker-1] Error retrieving new torrent, will try again in 10 sec...[2017-10-21 18:02:38,448: WARNING/PoolWorker-1] bad hash parameter
[2017-10-21 18:02:38,448: WARNING/PoolWorker-1] Error retrieving new torrent, will try again in 10 sec...[2017-10-21 18:02:49,475: WARNING/PoolWorker-1] bad hash parameter
[2017-10-21 18:02:49,475: WARNING/PoolWorker-1] Error retrieving new torrent, will try again in 10 sec...[2017-10-21 18:03:00,675: WARNING/PoolWorker-1] bad hash parameter
[2017-10-21 18:03:00,675: WARNING/PoolWorker-1] Error retrieving new torrent, will try again in 10 sec...[2017-10-21 18:03:12,094: WARNING/PoolWorker-1] bad hash parameter
[2017-10-21 18:03:12,095: WARNING/PoolWorker-1] Error retrieving new torrent, will try again in 10 sec...[2017-10-21 18:03:23,504: WARNING/PoolWorker-1] bad hash parameter
[2017-10-21 18:03:23,504: WARNING/PoolWorker-1] Error retrieving new torrent, will try again in 10 sec...[2017-10-21 18:03:34,594: ERROR/MainProcess] Task what_transcode.tasks.transcode[89a776c9-c254-421a-8576-cd723931503a] raised unexpected: Exception(u'Error uploading data to Redacted. Errors: ',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home//gits/WhatManager2/what_transcode/tasks.py", line 392, in transcode
    job.run()
  File "/home//gits/WhatManager2/what_transcode/tasks.py", line 350, in run
    self.transcode_upload_lossless(temp_dir)
  File "/home//gits/WhatManager2/what_transcode/tasks.py", line 385, in transcode_upload_lossless
    single_job.run()
  File "/home//gits/WhatManager2/what_transcode/tasks.py", line 120, in run
    self.upload_torrent()
  File "/home//gits/WhatManager2/what_transcode/tasks.py", line 226, in upload_torrent
    raise ex
Exception: Error uploading data to Redacted. Errors:```

**Comment by Mechazawa** [comment]
Odd, I'll have a look at this tonight or tomorrow probably.

**Comment by montchr** [comment]
I've also encountered this issue. Any suggestions?

**Comment by montchr** [comment]
Looks like this is addressed [in the wiki](https://github.com/karamanolev/WhatManager2/wiki/Troubleshooting#failed---exception-error-uploading-data-to-whatcd-errors-no-further-info). That solution fixed the issue for me.
