### ISSUE TITLE
Error adding new torrent during winter time shift

### ISSUE THREAD

**Issue by OdinGitDat** [karamanolev/WhatManager2#125]
Since today any torrent I try to add gives the same error (except timestamp at the end).

```
Traceback (most recent call last):
  File "/home/odin/WhatManager2/what_json/views.py", line 183, in add_torrent
    m_torrent = manage_torrent.add_torrent(request, instance, download_location, what_id, True)
  File "/home/odin/WhatManager2/WhatManager2/manage_torrent.py", line 48, in add_torrent
    norm_t_torrent(t_torrent)
  File "/home/odin/WhatManager2/WhatManager2/utils.py", line 54, in norm_t_torrent
    t.date_added_tz = timezone.make_aware(t.date_added, timezone.get_default_timezone())
  File "/usr/local/lib/python2.7/dist-packages/django/utils/timezone.py", line 358, in make_aware
    return timezone.localize(value, is_dst=None)
  File "/usr/local/lib/python2.7/dist-packages/pytz/tzinfo.py", line 363, in localize
    raise AmbiguousTimeError(dt)
AmbiguousTimeError: 2019-10-27 02:40:01
```

AmbigiousTimeError? I suspect it has something to do with the change to wintertime today. Not sure how to fix this.

**Comment by OdinGitDat** [comment]
This only happens during the hour that occurs twice (at 3am the clock is put back to 2am).
