### ISSUE TITLE
home.models.DoesNotExist: ReplicaSet matching query does not exist

### ISSUE THREAD

**Issue by Frogdo** [karamanolev/WhatManager2#56]
I've followed the installation guide up to [step 12](https://github.com/karamanolev/WhatManager2/wiki/Installing-WM-Core), and I get the error `Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/mnt/tank/lamp/django/WhatManager2/WhatManager2/management/commands/transmission_new.py", line 26, in handle
    replica_set = models.ReplicaSet.objects.get(zone=zone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
home.models.DoesNotExist: ReplicaSet matching query does not exist.
`
I get the same error both with and without adding the DownloadLocation.

Sorry if I'm just missing a step.

Thanks.

**Comment by MADindustries** [comment]
You likely have an issue getting your transmission instances running. This has been quite common. Please join the #WM2-Support channel on http://irc.p2p-network.net/

We have several people who can assist you with this.

**Comment by mzlumin** [comment]
This also happens if the download location is not marked as preferred...

**Comment by karamanolev** [comment]
Guys, with the latest version from master the ReplicaSet and DownloadLocation zone is now passtheheadphones.me. I'll edit the wiki soon.

**Comment by MADindustries** [comment]
Update: ReplicaSet and DownloadLocation zone are now redacted.ch.

Also, those of you **looking for WM2 support** should now join **#wm2** on the redacted irc network: irc.scratch-network.net.
