### ISSUE TITLE
ImportError: cannot import name settings

### ISSUE THREAD

**Issue by talentedmrripley** [karamanolev/WhatManager2#64]
Getting the below error when trying to run ./manage.py migrate

ripley@whatmanager:/opt/wm/WhatManager2$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/wm/WhatManager2/qobuz2/models.py", line 15, in <module>
    from qobuz2 import settings
ImportError: cannot import name settings

**Comment by talentedmrripley** [comment]
Turns out the issue was that in the qobuz2 folder I needed to copy the settings.example.py to settings.py.  This issue can be closed.
