### ISSUE TITLE
./manage.py fails unless all settings.example.py files are copied to settings.py

### ISSUE THREAD

**Issue by mlapaglia** [karamanolev/WhatManager2#92]
The wiki instructions say I don't need to copy anonymouse bibliotik etc settings files unless I am using them, but the manage.py fails unless they are 

```Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mlapaglia/WhatManager2/qobuz2/models.py", line 15, in <module>
    from qobuz2 import settings```

**Comment by casedefault** [comment]
You're right, this always seems to be the case. The wiki seems to be wrong but it would be nice if the code could be changed to make the wiki right rather than the other way around 😃
